# Generated by Django 5.1.6 on 2025-03-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_name', models.CharField(max_length=100)),
                ('M_lang', models.CharField(max_length=100)),
                ('Director', models.CharField(max_length=100)),
                ('Released_date', models.DateField()),
                ('Genre', models.CharField(max_length=100)),
            ],
        ),
    ]
