# Generated by Django 5.1.6 on 2025-03-22 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_images'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '⭐ 1'), (2, '⭐⭐ 2'), (3, '⭐⭐⭐ 3'), (4, '⭐⭐⭐⭐ 4'), (5, '⭐⭐⭐⭐⭐ 5')])),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie_App.movies')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'movie_id')},
            },
        ),
    ]
